# Configuration file for the admin server
server:
  port: 8080

jwt:
  key: "CvXPiv34e2474LC5Xj7IP"  # Change this key before deployment
  expiration: "12h"  # JWT token expiration time

redis:
  host: "127.0.0.1:6379"  # Redis server address
  password: "izpXvn894uW2HFbyP5OGr"  # Redis password

postgres:
  host: "127.0.0.1"
  user: "postgres"
  password: "kL81xnDWo221FHFRX8GnP"  # PostgreSQL password
  dbname: "server"
  port: 5432
  sslmode: "disable"
  timezone: "Asia/Shanghai"

admin:
  password: "123456"  # Admin password - MUST be changed in production
  salt: "rHECMvW3el1zhpdzgx9dY"  # Password salt - MUST be regenerated and kept secret