# Configuration file for the admin server
server:
  port: 8080

jwt:
  key: "CvXPiv34e2474LC5Xj7IP"  # Change this key before deployment
  expiration: "12h"  # JWT token expiration time

redis:
  host: "127.0.0.1:6379"  # Redis server address
  password: "izpXvn894uW2HFbyP5OGr"  # Redis password

postgres:
  host: "127.0.0.1"
  user: "postgres"
  password: "kL81xnDWo221FHFRX8GnP"  # PostgreSQL password
  dbname: "server"
  port: 5432
  sslmode: "disable"
  timezone: "Asia/Shanghai"

admin:
  password: "123456"  # Admin password - MUST be changed in production
  salt: "rHECMvW3el1zhpdzgx9dY"  # Password salt - MUST be regenerated and kept secret

rate_limit:
  login_rate_per_minute: 30    # Maximum login attempts per minute per IP
  login_burst_size: 60         # Burst size for login requests
  general_rate_per_sec: 100    # Maximum general API requests per second per IP
  general_burst_size: 200      # Burst size for general API requests

tenant:
  min_query_length: 3          # Minimum length of input for tenant code search (must be met or exceeded)
  default_code: "system"       # System default tenant code
